// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZJL399Bo_iifHnw2fYlRqa2fDhYs3gQw',
    appId: '1:278385676404:web:8bc6184e689847dff38121',
    messagingSenderId: '278385676404',
    projectId: 'battleshipgame-881fd',
    authDomain: 'battleshipgame-881fd.firebaseapp.com',
    storageBucket: 'battleshipgame-881fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi5J9ZMjgR4UCeolmurdkfqv5gW0SibHs',
    appId: '1:278385676404:android:07518ca986dc6450f38121',
    messagingSenderId: '278385676404',
    projectId: 'battleshipgame-881fd',
    storageBucket: 'battleshipgame-881fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpbI37daSwH7PnkjcsghltrDctqSbXB5s',
    appId: '1:278385676404:ios:7d1f201c3431c3d1f38121',
    messagingSenderId: '278385676404',
    projectId: 'battleshipgame-881fd',
    storageBucket: 'battleshipgame-881fd.appspot.com',
    iosBundleId: 'com.example.battleshipGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpbI37daSwH7PnkjcsghltrDctqSbXB5s',
    appId: '1:278385676404:ios:7d1f201c3431c3d1f38121',
    messagingSenderId: '278385676404',
    projectId: 'battleshipgame-881fd',
    storageBucket: 'battleshipgame-881fd.appspot.com',
    iosBundleId: 'com.example.battleshipGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZJL399Bo_iifHnw2fYlRqa2fDhYs3gQw',
    appId: '1:278385676404:web:1f2548003e815d32f38121',
    messagingSenderId: '278385676404',
    projectId: 'battleshipgame-881fd',
    authDomain: 'battleshipgame-881fd.firebaseapp.com',
    storageBucket: 'battleshipgame-881fd.appspot.com',
  );
}
